# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ee9e7bff79684081a2dcf89358730f9a398b6931e54cb546cda98664a584dc5c4ef31fdef45557e13fc003489aaea92610d025668bf702edc7c213d177717a2

test:
  secret_key_base: 5a4fbdb07af06a86dfb414d9c099432a33fafced51eb0c23651a6b780fd816a47e5f709de8e8f746f02973802492eb9866e0e5127e2bf790ffea08877494f3a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
